mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path
from .views import index
from .views import other_page
from .views import BBLoginView
from .views import profile
from .views import logout_view
from .views import ChangeUserInfoView
from .views import BBPasswordChangeView
from .views import RegisterUserView, RegisterDoneView
from .views import user_activate
from .views import DeleteUserView
from .views import question_bb_add


from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login', BBLoginView.as_view(), name='login'),
    path('accounts/logout/', logout_view, name='logout'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/questions/add', question_bb_add, name='question_bb_add'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register_user'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser, User
from django.dispatch import Signal
from .utilities import send_activation_notification

class AdvUser(AbstractUser):
    photo = models.ImageField(upload_to='photos/', blank=True, null=True)
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name="Прошёл активацию?")
    send_messages = models.BooleanField(default=True, verbose_name="Оповещать при новых комментариях?")

    class Meta(AbstractUser.Meta):
        pass

user_registrated = Signal(['instance'])

def user_registrated_dispatcher(sender, **kwargs):
    send_activation_notification(kwargs["instance"])

user_registrated.connect(user_registrated_dispatcher)

class Question(models.Model):
    title = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='photos/', blank=True, null=True)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Вопрос')
    choice_text = models.CharField(max_length=200, verbose_name='Варианты ответа')
    votes = models.IntegerField(default=0, verbose_name='Голос')
    user = models.ForeignKey(AdvUser, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from .models import AdvUser
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .models import user_registrated
from .models import Question
from django.forms import inlineformset_factory
from .models import Choice


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='дрес электронной почты')
    photo = forms.ImageField(required=True)

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'photo', 'send_messages')

class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True,label="Адрес электронной почты")
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput, help_text = password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label="Пароль (повторно)", widget=forms.PasswordInput, help_text = "Повторите пароль")

    def clean_password(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2':ValidationError(
                "Введенные пароли не совпадают", code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=True)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        user.is_activated = True
        if commit:
            user.save()
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'photo', 'send_messages')

class QuestionForm(forms.ModelForm):
    photo = forms.ImageField(required=False, label='Фотография')
    class Meta:
        model = Question
        fields = ['title', 'question_text', 'photo']
        labels = {
            'title': 'Заголовок',
            'question_text': 'Описание',
            'photo': 'Фотография',
        }
        widgets = {
            'question_text': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.HiddenInput(attrs={'class': 'form-control'})
        }

ChoiceFormSet = inlineformset_factory(Question, Choice, fields=('choice_text',))

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import Question, Choice
from django.template import TemplateDoesNotExist
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import UpdateView
from .forms import ChangeUserInfoForm, QuestionForm, ChoiceFormSet
from .models import AdvUser
from django.contrib.auth.views import PasswordChangeView
from django.views.generic.edit import CreateView
from .forms import RegisterUserForm
from django.views.generic.base import TemplateView, View
from django.core.signing import BadSignature
from .utilities import signer
from django.views.generic import DeleteView
from django.contrib import messages


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question = self.object

        total_votes = sum(choice.votes for choice in question.choice_set.all())

        choices_with_percent = []
        for choice in question.choice_set.all():
            percent = round(choice.votes / total_votes * 100, 1) if total_votes > 0 else 0
            choices_with_percent.append({
                'choice': choice,
                'percent': percent
            })

        context['choices_with_percent'] = choices_with_percent
        context['total_votes'] = total_votes
        return context


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if Choice.objects.filter(question=question, user=request.user).exists():
        messages.error(request, "Вы уже голосовали в этом опросе.Результаты ниже.")
        return render(request, 'polls/detail.html', {
            'question': question,
            'already_voted': True,
            'error_message': "Вы уже голосовали."
        })
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'вы не сделали выбор'
        })
    else:
        selected_choice.votes += 1
        selected_choice.user = request.user
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def index(request):
    return render(request, 'polls/index.html')

def other_page(request, page):
    try:
        template = get_template('polls/' + page +'.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request = request))

class BBLoginView(LoginView):
    template_name = 'polls/login.html'

@login_required
def profile(request):
    return render(request, 'polls/profile.html')

def logout_view(request):
    logout(request)
    return redirect('/')

class ChangeUserInfoView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = AdvUser
    template_name = 'polls/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('polls:profile')
    success_message = "Личные данные пользователя изменены"

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'polls/password_change.html'

class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'polls/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('polls:login')

class RegisterDoneView(TemplateView):
    template_name = 'polls/register_done.html'

def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'polls/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'polls/user_is_activated.html'
    else:
        template = 'polls/activation_done.html'
        user.is_activated = True
        user.is_active = True
        user.save()
    return render(request, template)

class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'polls/delete_user.html'
    success_url = reverse_lazy('polls:index')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request,messages.SUCCESS,"Пользователь удалён")
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class CreateQuestionView(CreateView):
    model = Question
    template_name = 'polls/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('polls:login')

# @login_required(login_url='polls:login')
# def question_bb_add(request):
#     if request.method == 'POST':
#         form = QuestionForm(request.POST, request.FILES)
#         if form.is_valid():
#             bb = form.save()
#             formset = ChoiceFormSet(request.POST, request.FILES, instance=bb)
#             if formset.is_valid():
#                 formset.save()
#                 messages.add_message(request,messages.SUCCESS, "Вопрос добавлен")
#                 return redirect('polls:index')
#     else:
#         form = QuestionForm(initial={'author': request.user.pk})
#         formset = ChoiceFormSet()
#     context = {'form': form, 'formset': formset}
#     return render(request, 'polls/question_bb_add.html', context)


@login_required(login_url='polls:login')
def question_bb_add(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user

            formset = ChoiceFormSet(request.POST, instance=question)
            if formset.is_valid():
                question.save()
                formset.save()
                messages.success(request, "Вопрос добавлен")
                return redirect('polls:index')
    else:
        form = QuestionForm()
        formset = ChoiceFormSet()

    return render(request, 'polls/question_bb_add.html', {
        'form': form,
        'formset': formset
    })

polls/templates/polls/activation_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Активация</title>
</head>
<body>
<h2>Активация</h2>
<p>Активация пользователя завершена</p>
<p><a href="{% url 'polls:login' %}">Войти на сайт</a></p>
</body>
</html>

polls/templates/polls/bad_signature.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ошибка активации</title>
</head>
<body>
<h2>Активация</h2>
<p>Регистрация пользователя прошла неудачно.</p>
<p><a href="{% url 'polls:register_user' %}">Зарегистрироваться повторно</a></p>
</body>
</html>

polls/templates/polls/change_user_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Правка личных данных</title>
</head>
<body>
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="hidden" name="next" value="{{ next }}">
    <input type="submit" value="Сохранить">
</form>

</body>
</html>

polls/templates/polls/delete_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Удаление пользователя {{ object.username }}</h2>
<form method="post">
{% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    <input type="submit" value="Удалить"></form>
</body>
</html>

polls/templates/polls/detail.html
<style>
    .question-photo {
        width: 500px;
        height: 500px;
        object-fit: cover;
    }
</style>

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            {% if question.photo %}
                <img src="{{ question.photo.url }}" class="question-photo" alt="Фото к опросу">
            {% endif %}
            <h1>{{ question.title }}</h1>
            <h2>{{ question.question_text }}</h2>
        </legend>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        {% if already_voted %}
            <p>Вы уже приняли участие в этом опросе.</p>
            <p><a href="{% url 'polls:results' question.id %}">Посмотреть результаты</a></p>
        {% else %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        {% endif %}
    </fieldset>

    {% if not already_voted %}
        <input type="submit" value="Голосовать">
        <br>
    {% endif %}

    <a href="{% url 'polls:index' %}">На главную</a>
</form>

polls/templates/polls/index.html
<a href="{% url 'polls:login' %}">Вход</a>
<a href="{% url 'polls:register_user' %}">Регистрация</a>
<a href="{% url 'polls:profile' %}">Профиль</a>
<a href="{% url 'polls:question_bb_add' %}">Добавить вопрос</a>
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>
    Вопросов нет!!
</p>

{% endif %}

<a href="{% url 'polls:logout' %}">Выход</a>

polls/templates/polls/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
</head>
<body>
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="hidden" name="next" value="{{ next }}">
    <input type="submit" value="Войти">
</form>
{% endif %}

</body>
</html>

polls/templates/polls/password_change.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Смена пароля</title>
</head>
<body>
<h2>Смена пароля пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="hidden" name="next" value="{{ next }}">
    <input type="submit" value="Изменить">
</form>
</body>
</html>

polls/templates/polls/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Профиль</title>
    <style>
    .profile-photo {
        width: 150px;
        height: 150px;
        object-fit: cover;
        border-radius: 50%;
    }
  </style>
</head>
<body>
    <h2>Профиль пользователя {{ user.username }}</h2>
    <img src="{{ user.photo.url }}" class="profile-photo" alt="">
    {% if user.first_name and user.last_name %}
        <p>Здравствуйте, {{ user.first_name }} {{ user.last_name }} </p>
        <a href="{% url 'polls:profile_change' %}">Изменить данные<br></a>
    <a href="{% url 'polls:password_change' %}">Изменить пароль<br></a>
    <a href="{% url 'polls:profile_delete' %}">Удалить профиль<br></a>

    {% else %}
        <p>Здравствуйте! </p>
    <a href="{% url 'polls:profile_change' %}">Изменить данные<br></a>
    <a href="{% url 'polls:password_change' %}">Изменить пароль<br></a>
    <a href="{% url 'polls:profile_delete' %}">Удалить профиль<br></a>

    {% endif %}
        <a href="{% url 'polls:index' %}">На главную</a>

</body>
</html>

polls/templates/polls/question_bb_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добавить вопрос</title>
</head>
<body>
<h2>Добавление вопроса</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    {{formset}}
    <input type="submit" value="Добавить">

</form>
</body>
</html>

polls/templates/polls/register_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Завершение регистрации</title>
</head>
<body>
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена</p>
<p>На адрес электронной почты, указанный пользователем, выслано письмо для
    активации</p>
</body>
</html>

polls/templates/polls/register_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>
<h2>Регистрация нового пользователя</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Зарегистрироваться">
</form>
</body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for item in choices_with_percent %}
    <li>{{ item.choice.choice_text }} -- {{ item.choice.votes }} vote{{ item.choice.votes|pluralize }} ({{ item.percent }}%)</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">выбрать еще раз? </a>
<br>
<a href="{% url 'polls:index' %}">на главную</a>

polls/templates/polls/user_is_activated.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Пользователь активирован</title>
</head>
<body>
<h2>Активация</h2>
<p>Пользователь с таким именем уже был активирован ранее.</p>
<p><a href="{% url 'polls:login' %}">Войти на сайт</a></p>

</body>
</html>